"""Task definitions organized by category for the BenchAgent benchmark."""

from __future__ import annotations

from bench_agent.models import Difficulty, Task, TaskCategory

# ── BASH TASKS (21 tasks) ────────────────────────────────────────────

BASH_TASKS: list[Task] = [
    Task(
        task_id="bash-001",
        category=TaskCategory.BASH,
        difficulty=Difficulty.EASY,
        description="Find all Python files in the project directory that contain the word 'import'",
        initial_state={
            "main.py": "import os\nimport sys\n\ndef main():\n    print('hello')\n",
            "utils.py": "import json\n\ndef parse(s):\n    return json.loads(s)\n",
            "README.md": "# Project\n\nimport is a keyword in Python.\n",
        },
        expected_outcome={"files": ["main.py", "utils.py"]},
        tools_required=["bash"],
        max_turns=3,
        verification_script="import os; files=[f for f in os.listdir('.') if f.endswith('.py')]; "
        "py_files=[f for f in files if 'import' in open(f).read()]; "
        "assert sorted(py_files) == ['main.py', 'utils.py']",
    ),
    Task(
        task_id="bash-002",
        category=TaskCategory.BASH,
        difficulty=Difficulty.EASY,
        description="Count the total number of lines across all Python files in the directory",
        initial_state={
            "a.py": "line1\nline2\nline3\n",
            "b.py": "line1\nline2\n",
        },
        expected_outcome={"stdout_pattern": "5"},
        tools_required=["bash"],
        max_turns=3,
        verification_script="import glob; total=sum(1 for f in glob.glob('*.py') for _ in open(f)); assert total == 5",
    ),
    Task(
        task_id="bash-003",
        category=TaskCategory.BASH,
        difficulty=Difficulty.EASY,
        description="List all files sorted by size (smallest first)",
        initial_state={
            "small.txt": "hi\n",
            "medium.txt": "hello world\n",
            "large.txt": "a" * 500 + "\n",
        },
        expected_outcome={"stdout_contains": ["small.txt", "medium.txt", "large.txt"]},
        tools_required=["bash"],
        max_turns=3,
        verification_script="pass",
    ),
    Task(
        task_id="bash-004",
        category=TaskCategory.BASH,
        difficulty=Difficulty.EASY,
        description="Find and replace all occurrences of 'TODO' with 'DONE' in all Python files",
        initial_state={
            "app.py": "TODO: fix this\nTODO: add tests\nx = 1\n",
        },
        expected_outcome={"files": {"app.py": "DONE: fix this\nDONE: add tests\nx = 1\n"}},
        tools_required=["bash"],
        max_turns=3,
        verification_script="assert 'TODO' not in open('app.py').read() and 'DONE' in open('app.py').read()",
    ),
    Task(
        task_id="bash-005",
        category=TaskCategory.BASH,
        difficulty=Difficulty.MEDIUM,
        description="Extract all unique email addresses from all text files in the directory",
        initial_state={
            "contacts.txt": "Reach us at alice@example.com or bob@example.com\ncc: carol@example.com\n",
            "notes.txt": "Support: support@corp.io\nalice@example.com again\n",
        },
        expected_outcome={"stdout_contains": ["alice@example.com", "bob@example.com", "carol@example.com", "support@corp.io"]},
        tools_required=["bash"],
        max_turns=5,
        verification_script="import re; emails=set(); "
        "[emails.update(re.findall(r'[\\w.+-]+@[\\w-]+\\.[\\w.]+', open(f).read())) for f in ['contacts.txt','notes.txt']]; "
        "assert len(emails) == 4",
    ),
    Task(
        task_id="bash-006",
        category=TaskCategory.BASH,
        difficulty=Difficulty.MEDIUM,
        description="Create a directory structure: src/lib, src/tests, docs, and create an empty __init__.py in each Python directory",
        initial_state={},
        expected_outcome={"file_exists": ["src/lib/__init__.py", "src/tests/__init__.py", "docs"]},
        tools_required=["bash"],
        max_turns=5,
        verification_script="import os; assert os.path.isdir('src/lib'); assert os.path.isdir('src/tests'); "
        "assert os.path.isdir('docs'); assert os.path.exists('src/lib/__init__.py'); assert os.path.exists('src/tests/__init__.py')",
    ),
    Task(
        task_id="bash-007",
        category=TaskCategory.BASH,
        difficulty=Difficulty.MEDIUM,
        description="Find all Python files with syntax errors and list them",
        initial_state={
            "good.py": "x = 1\ny = 2\n",
            "bad.py": "def foo(\n  x = 1\n",
            "also_good.py": "z = 3\n",
        },
        expected_outcome={"stdout_contains": ["bad.py"]},
        tools_required=["bash"],
        max_turns=5,
        verification_script="pass",
    ),
    Task(
        task_id="bash-008",
        category=TaskCategory.BASH,
        difficulty=Difficulty.MEDIUM,
        description="Calculate the total disk usage of all .log files in the directory tree",
        initial_state={
            "app.log": "entry\n" * 100,
            "error.log": "error\n" * 50,
            "sub/debug.log": "debug\n" * 200,
        },
        expected_outcome={"stdout_pattern": r"\d+"},
        tools_required=["bash"],
        max_turns=3,
        verification_script="import os; total=sum(os.path.getsize(os.path.join(dp,f)) for dp,dn,fn in os.walk('.') for f in fn if f.endswith('.log')); assert total > 0",
    ),
    Task(
        task_id="bash-009",
        category=TaskCategory.BASH,
        difficulty=Difficulty.HARD,
        description="Find the top 5 most common words across all text files, excluding stop words (the, a, an, is, are, was, were, in, on, at, to, for, of, and)",
        initial_state={
            "article1.txt": "the quick brown fox jumps over the lazy dog and the dog was not happy",
            "article2.txt": "a fox is a quick animal and the brown fox is very clever",
        },
        expected_outcome={"stdout_contains": ["fox"]},
        tools_required=["bash"],
        max_turns=5,
        verification_script="pass",
    ),
    Task(
        task_id="bash-010",
        category=TaskCategory.BASH,
        difficulty=Difficulty.MEDIUM,
        description="Archive all .py files into a tarball named backup.tar.gz preserving directory structure",
        initial_state={
            "src/main.py": "print('main')\n",
            "src/lib/helpers.py": "def help(): pass\n",
        },
        expected_outcome={"file_exists": ["backup.tar.gz"]},
        tools_required=["bash"],
        max_turns=5,
        verification_script="import os; assert os.path.exists('backup.tar.gz')",
    ),
    Task(
        task_id="bash-011",
        category=TaskCategory.BASH,
        difficulty=Difficulty.EASY,
        description="Show the current working directory",
        initial_state={},
        expected_outcome={"exit_code": 0},
        tools_required=["bash"],
        max_turns=2,
        verification_script="pass",
    ),
    Task(
        task_id="bash-012",
        category=TaskCategory.BASH,
        difficulty=Difficulty.EASY,
        description="Create a file called hello.txt with the content 'Hello, World!'",
        initial_state={},
        expected_outcome={"files": {"hello.txt": "Hello, World!"}},
        tools_required=["bash"],
        max_turns=2,
        verification_script="assert open('hello.txt').read().strip() == 'Hello, World!'",
    ),
    Task(
        task_id="bash-013",
        category=TaskCategory.BASH,
        difficulty=Difficulty.MEDIUM,
        description="Find all files modified in the last 24 hours and list their names",
        initial_state={
            "recent.py": "# newly created\n",
            "old.py": "# old file\n",
        },
        expected_outcome={"stdout_contains": ["recent.py"]},
        tools_required=["bash"],
        max_turns=3,
        verification_script="pass",
    ),
    Task(
        task_id="bash-014",
        category=TaskCategory.BASH,
        difficulty=Difficulty.HARD,
        description="Parse a CSV file and output only rows where the 'age' column is greater than 30",
        initial_state={
            "data.csv": "name,age,city\nAlice,25,NYC\nBob,35,LA\nCarol,42,Chicago\nDave,28,Seattle\nEve,50,Boston\n",
        },
        expected_outcome={"stdout_contains": ["Bob", "Carol", "Eve"]},
        tools_required=["bash"],
        max_turns=5,
        verification_script="pass",
    ),
    Task(
        task_id="bash-015",
        category=TaskCategory.BASH,
        difficulty=Difficulty.HARD,
        description="Convert all .md files to .html using a basic Markdown-to-HTML transformation (paragraphs, headers, bold)",
        initial_state={
            "doc.md": "# Title\n\nThis is **bold** text.\n\nAnother paragraph.\n",
        },
        expected_outcome={"file_exists": ["doc.html"]},
        tools_required=["bash"],
        max_turns=8,
        verification_script="import os; assert os.path.exists('doc.html')",
    ),
    Task(
        task_id="bash-016",
        category=TaskCategory.BASH,
        difficulty=Difficulty.MEDIUM,
        description="Find duplicate files by content hash across the directory",
        initial_state={
            "a.txt": "hello world\n",
            "b.txt": "hello world\n",
            "c.txt": "different content\n",
        },
        expected_outcome={"stdout_contains": ["a.txt", "b.txt"]},
        tools_required=["bash"],
        max_turns=5,
        verification_script="pass",
    ),
    Task(
        task_id="bash-017",
        category=TaskCategory.BASH,
        difficulty=Difficulty.EASY,
        description="Concatenate all .txt files in alphabetical order into a single file called merged.txt",
        initial_state={
            "alpha.txt": "aaa\n",
            "beta.txt": "bbb\n",
            "gamma.txt": "ccc\n",
        },
        expected_outcome={"files": {"merged.txt": "aaa\nbbb\nccc\n"}},
        tools_required=["bash"],
        max_turns=3,
        verification_script="content=open('merged.txt').read(); assert 'aaa' in content and 'bbb' in content and 'ccc' in content",
    ),
    Task(
        task_id="bash-018",
        category=TaskCategory.BASH,
        difficulty=Difficulty.HARD,
        description="Monitor a log file and extract all ERROR lines with timestamps, outputting them as JSON",
        initial_state={
            "app.log": "2024-01-15 10:00:00 INFO Starting app\n2024-01-15 10:01:00 ERROR Database connection failed\n2024-01-15 10:02:00 INFO Retrying\n2024-01-15 10:03:00 ERROR Timeout exceeded\n",
        },
        expected_outcome={"stdout_contains": ["Database connection failed", "Timeout exceeded"]},
        tools_required=["bash"],
        max_turns=5,
        verification_script="pass",
    ),
    Task(
        task_id="bash-019",
        category=TaskCategory.BASH,
        difficulty=Difficulty.MEDIUM,
        description="Sort a file containing numbers, one per line, in descending order",
        initial_state={
            "numbers.txt": "42\n7\n100\n3\n99\n1\n55\n",
        },
        expected_outcome={"stdout_contains": ["100", "99", "55", "42"]},
        tools_required=["bash"],
        max_turns=3,
        verification_script="pass",
    ),
    Task(
        task_id="bash-020",
        category=TaskCategory.BASH,
        difficulty=Difficulty.MEDIUM,
        description="Extract all URLs from an HTML file",
        initial_state={
            "page.html": '<html><a href="https://example.com">Link 1</a><img src="https://img.example.com/photo.jpg"/><a href="https://test.org">Link 2</a></html>',
        },
        expected_outcome={"stdout_contains": ["https://example.com", "https://test.org"]},
        tools_required=["bash"],
        max_turns=5,
        verification_script="pass",
    ),
    Task(
        task_id="bash-021",
        category=TaskCategory.BASH,
        difficulty=Difficulty.HARD,
        description="Write a shell one-liner that counts the frequency of each word in a file and outputs the top 10",
        initial_state={
            "text.txt": "the cat sat on the mat the cat was black the mat was flat cat cat cat",
        },
        expected_outcome={"stdout_contains": ["cat"]},
        tools_required=["bash"],
        max_turns=5,
        verification_script="pass",
    ),
]

# ── EDIT TASKS (22 tasks) ────────────────────────────────────────────

EDIT_TASKS: list[Task] = [
    Task(
        task_id="edit-001",
        category=TaskCategory.EDIT,
        difficulty=Difficulty.EASY,
        description="Fix the off-by-one error in the loop: it should iterate range(len(items)) not range(len(items)+1)",
        initial_state={
            "app.py": "def get_all(items):\n    result = []\n    for i in range(len(items) + 1):\n        result.append(items[i])\n    return result\n",
        },
        expected_outcome={"files": {"app.py": "def get_all(items):\n    result = []\n    for i in range(len(items)):\n        result.append(items[i])\n    return result\n"}},
        tools_required=["edit"],
        max_turns=3,
        verification_script="assert 'range(len(items))' in open('app.py').read()",
    ),
    Task(
        task_id="edit-002",
        category=TaskCategory.EDIT,
        difficulty=Difficulty.EASY,
        description="Replace the bare 'except:' clause with 'except Exception:' to avoid catching SystemExit and KeyboardInterrupt",
        initial_state={
            "handler.py": "try:\n    do_something()\nexcept:\n    log_error()\n",
        },
        expected_outcome={"files": {"handler.py": "try:\n    do_something()\nexcept Exception:\n    log_error()\n"}},
        tools_required=["edit"],
        max_turns=3,
        verification_script="assert 'except Exception:' in open('handler.py').read()",
    ),
    Task(
        task_id="edit-003",
        category=TaskCategory.EDIT,
        difficulty=Difficulty.MEDIUM,
        description="Add input validation to the divide function: raise ValueError if divisor is zero",
        initial_state={
            "math_ops.py": "def divide(a, b):\n    return a / b\n",
        },
        expected_outcome={"files": {"math_ops.py": "def divide(a, b):\n    if b == 0:\n        raise ValueError('Cannot divide by zero')\n    return a / b\n"}},
        tools_required=["edit"],
        max_turns=3,
        verification_script="code=open('math_ops.py').read(); assert 'ValueError' in code or 'raise' in code",
    ),
    Task(
        task_id="edit-004",
        category=TaskCategory.EDIT,
        difficulty=Difficulty.MEDIUM,
        description="Refactor the User class to use dataclass syntax",
        initial_state={
            "models.py": "class User:\n    def __init__(self, name, email, age):\n        self.name = name\n        self.email = email\n        self.age = age\n\n    def __repr__(self):\n        return f'User(name={self.name!r}, email={self.email!r}, age={self.age})'\n",
        },
        expected_outcome={"files": {"models.py": "from dataclasses import dataclass\n\n@dataclass\nclass User:\n    name: str\n    email: str\n    age: int\n"}},
        tools_required=["edit"],
        max_turns=5,
        verification_script="code=open('models.py').read(); assert '@dataclass' in code or 'dataclass' in code",
    ),
    Task(
        task_id="edit-005",
        category=TaskCategory.EDIT,
        difficulty=Difficulty.EASY,
        description="Fix the string formatting: change from %s to f-string",
        initial_state={
            "greet.py": "def greet(name):\n    return 'Hello, %s!' % name\n",
        },
        expected_outcome={"files": {"greet.py": "def greet(name):\n    return f'Hello, {name}!'\n"}},
        tools_required=["edit"],
        max_turns=3,
        verification_script="code=open('greet.py').read(); assert 'f\\'' in code or 'f\"' in code",
    ),
    Task(
        task_id="edit-006",
        category=TaskCategory.EDIT,
        difficulty=Difficulty.MEDIUM,
        description="Add type hints to all function parameters and return values",
        initial_state={
            "utils.py": "def add(a, b):\n    return a + b\n\ndef greet(name):\n    return f'Hello, {name}'\n\ndef process(items, key):\n    return sorted(items, key=key)\n",
        },
        expected_outcome={"files": {"utils.py": "def add(a: int, b: int) -> int:\n    return a + b\n\ndef greet(name: str) -> str:\n    return f'Hello, {name}'\n\ndef process(items: list, key: callable) -> list:\n    return sorted(items, key=key)\n"}},
        tools_required=["edit"],
        max_turns=5,
        verification_script="code=open('utils.py').read(); assert '-> ' in code",
    ),
    Task(
        task_id="edit-007",
        category=TaskCategory.EDIT,
        difficulty=Difficulty.HARD,
        description="Convert the class-based BST to use comparable generic type hints and add a __contains__ method",
        initial_state={
            "bst.py": "class BST:\n    def __init__(self, value):\n        self.value = value\n        self.left = None\n        self.right = None\n\n    def insert(self, value):\n        if value < self.value:\n            if self.left is None:\n                self.left = BST(value)\n            else:\n                self.left.insert(value)\n        else:\n            if self.right is None:\n                self.right = BST(value)\n            else:\n                self.right.insert(value)\n",
        },
        expected_outcome={"files": {"bst.py": "from typing import TypeVar, Generic, Optional\n\nT = TypeVar('T')\n\nclass BST(Generic[T]):\n    def __init__(self, value: T):\n        self.value: T = value\n        self.left: Optional[BST[T]] = None\n        self.right: Optional[BST[T]] = None\n\n    def insert(self, value: T) -> None:\n        if value < self.value:\n            if self.left is None:\n                self.left = BST(value)\n            else:\n                self.left.insert(value)\n        else:\n            if self.right is None:\n                self.right = BST(value)\n            else:\n                self.right.insert(value)\n\n    def __contains__(self, value: T) -> bool:\n        if value == self.value:\n            return True\n        elif value < self.value and self.left is not None:\n            return value in self.left\n        elif value > self.value and self.right is not None:\n            return value in self.right\n        return False\n"}},
        tools_required=["edit"],
        max_turns=10,
        verification_script="code=open('bst.py').read(); assert '__contains__' in code and 'Generic' in code",
    ),
    Task(
        task_id="edit-008",
        category=TaskCategory.EDIT,
        difficulty=Difficulty.EASY,
        description="Change the API endpoint from /api/v1/users to /api/v2/users",
        initial_state={
            "routes.py": "USERS_ENDPOINT = '/api/v1/users'\nITEMS_ENDPOINT = '/api/v1/items'\n",
        },
        expected_outcome={"files": {"routes.py": "USERS_ENDPOINT = '/api/v2/users'\nITEMS_ENDPOINT = '/api/v1/items'\n"}},
        tools_required=["edit"],
        max_turns=3,
        verification_script="code=open('routes.py').read(); assert '/api/v2/users' in code",
    ),
    Task(
        task_id="edit-009",
        category=TaskCategory.EDIT,
        difficulty=Difficulty.MEDIUM,
        description="Add logging to all function entry points in the service module",
        initial_state={
            "service.py": "def create_user(name, email):\n    return {'name': name, 'email': email}\n\ndef delete_user(user_id):\n    return {'deleted': user_id}\n\ndef update_user(user_id, **kwargs):\n    return {'updated': user_id, **kwargs}\n",
        },
        expected_outcome={"files": {"service.py": "import logging\n\nlogger = logging.getLogger(__name__)\n\ndef create_user(name, email):\n    logger.info('Creating user: %s', name)\n    return {'name': name, 'email': email}\n\ndef delete_user(user_id):\n    logger.info('Deleting user: %s', user_id)\n    return {'deleted': user_id}\n\ndef update_user(user_id, **kwargs):\n    logger.info('Updating user: %s', user_id)\n    return {'updated': user_id, **kwargs}\n"}},
        tools_required=["edit"],
        max_turns=5,
        verification_script="code=open('service.py').read(); assert 'logging' in code and 'logger' in code",
    ),
    Task(
        task_id="edit-010",
        category=TaskCategory.EDIT,
        difficulty=Difficulty.HARD,
        description="Convert the function to async/await pattern, making the HTTP calls non-blocking",
        initial_state={
            "client.py": "import requests\n\ndef fetch_data(url):\n    response = requests.get(url)\n    return response.json()\n\ndef fetch_all(urls):\n    results = []\n    for url in urls:\n        results.append(fetch_data(url))\n    return results\n",
        },
        expected_outcome={"files": {"client.py": "import aiohttp\nimport asyncio\n\nasync def fetch_data(url):\n    async with aiohttp.ClientSession() as session:\n        async with session.get(url) as response:\n            return await response.json()\n\nasync def fetch_all(urls):\n    tasks = [fetch_data(url) for url in urls]\n    return await asyncio.gather(*tasks)\n"}},
        tools_required=["edit"],
        max_turns=8,
        verification_script="code=open('client.py').read(); assert 'async' in code and 'await' in code",
    ),
    Task(
        task_id="edit-011",
        category=TaskCategory.EDIT,
        difficulty=Difficulty.EASY,
        description="Fix the typo: 'recieve' should be 'receive'",
        initial_state={
            "email.py": "def recieve_email(address):\n    return f'Email sent to {address}'\n",
        },
        expected_outcome={"files": {"email.py": "def receive_email(address):\n    return f'Email sent to {address}'\n"}},
        tools_required=["edit"],
        max_turns=2,
        verification_script="code=open('email.py').read(); assert 'receive_email' in code and 'recieve' not in code",
    ),
    Task(
        task_id="edit-012",
        category=TaskCategory.EDIT,
        difficulty=Difficulty.MEDIUM,
        description="Add a docstring to each function in the module",
        initial_state={
            "calc.py": "def add(a, b):\n    return a + b\n\ndef subtract(a, b):\n    return a - b\n\ndef multiply(a, b):\n    return a * b\n",
        },
        expected_outcome={"stdout_contains": []},
        tools_required=["edit"],
        max_turns=5,
        verification_script="code=open('calc.py').read(); assert '\"\"\"' in code or \"'''\" in code",
    ),
    Task(
        task_id="edit-013",
        category=TaskCategory.EDIT,
        difficulty=Difficulty.HARD,
        description="Replace the custom implementation of merge_sort with Python's built-in sorted() and add a key parameter",
        initial_state={
            "sorter.py": "def merge_sort(arr):\n    if len(arr) <= 1:\n        return arr\n    mid = len(arr) // 2\n    left = merge_sort(arr[:mid])\n    right = merge_sort(arr[mid:])\n    return merge(left, right)\n\ndef merge(left, right):\n    result = []\n    i = j = 0\n    while i < len(left) and j < len(right):\n        if left[i] <= right[j]:\n            result.append(left[i])\n            i += 1\n        else:\n            result.append(right[j])\n            j += 1\n    result.extend(left[i:])\n    result.extend(right[j:])\n    return result\n",
        },
        expected_outcome={"files": {"sorter.py": "def merge_sort(arr, key=None):\n    return sorted(arr, key=key)\n"}},
        tools_required=["edit"],
        max_turns=5,
        verification_script="code=open('sorter.py').read(); assert 'sorted(' in code",
    ),
    Task(
        task_id="edit-014",
        category=TaskCategory.EDIT,
        difficulty=Difficulty.MEDIUM,
        description="Change the REST API from returning a list to returning a paginated response with metadata",
        initial_state={
            "api.py": "def get_users(db):\n    users = db.query('SELECT * FROM users')\n    return users\n",
        },
        expected_outcome={"files": {"api.py": "def get_users(db, page=1, per_page=20):\n    offset = (page - 1) * per_page\n    users = db.query('SELECT * FROM users LIMIT ? OFFSET ?', (per_page, offset))\n    total = db.query('SELECT COUNT(*) FROM users')[0]['count']\n    return {\n        'data': users,\n        'page': page,\n        'per_page': per_page,\n        'total': total,\n        'total_pages': (total + per_page - 1) // per_page,\n    }\n"}},
        tools_required=["edit"],
        max_turns=8,
        verification_script="code=open('api.py').read(); assert 'page' in code and 'per_page' in code",
    ),
    Task(
        task_id="edit-015",
        category=TaskCategory.EDIT,
        difficulty=Difficulty.EASY,
        description="Change the default port from 5000 to 8000",
        initial_state={
            "config.py": "HOST = '0.0.0.0'\nPORT = 5000\nDEBUG = False\n",
        },
        expected_outcome={"files": {"config.py": "HOST = '0.0.0.0'\nPORT = 8000\nDEBUG = False\n"}},
        tools_required=["edit"],
        max_turns=2,
        verification_script="code=open('config.py').read(); assert '8000' in code",
    ),
    Task(
        task_id="edit-016",
        category=TaskCategory.EDIT,
        difficulty=Difficulty.MEDIUM,
        description="Add error handling with custom exception class to the database module",
        initial_state={
            "database.py": "class Database:\n    def __init__(self, connection_string):\n        self.conn = connect(connection_string)\n\n    def query(self, sql):\n        cursor = self.conn.execute(sql)\n        return cursor.fetchall()\n",
        },
        expected_outcome={"files": {"database.py": "class DatabaseError(Exception):\n    pass\n\nclass Database:\n    def __init__(self, connection_string):\n        try:\n            self.conn = connect(connection_string)\n        except Exception as e:\n            raise DatabaseError(f'Failed to connect: {e}') from e\n\n    def query(self, sql):\n        try:\n            cursor = self.conn.execute(sql)\n            return cursor.fetchall()\n        except Exception as e:\n            raise DatabaseError(f'Query failed: {e}') from e\n"}},
        tools_required=["edit"],
        max_turns=6,
        verification_script="code=open('database.py').read(); assert 'DatabaseError' in code and 'raise' in code",
    ),
    Task(
        task_id="edit-017",
        category=TaskCategory.EDIT,
        difficulty=Difficulty.HARD,
        description="Refactor the monolithic function into smaller composable functions with proper separation of concerns",
        initial_state={
            "pipeline.py": "def process_data(raw_data, config):\n    # Parse\n    parsed = []\n    for item in raw_data:\n        if item.startswith('{'):\n            import json\n            parsed.append(json.loads(item))\n        else:\n            parsed.append({'value': item.strip()})\n    # Validate\n    validated = []\n    for item in parsed:\n        if 'value' in item and item['value']:\n            validated.append(item)\n    # Transform\n    transformed = []\n    for item in validated:\n        transformed.append({k: v.upper() if isinstance(v, str) else v for k, v in item.items()})\n    # Filter by config\n    filtered = [item for item in transformed if item.get('category', 'default') in config.get('categories', ['default'])]\n    return filtered\n",
        },
        expected_outcome={"files": {"pipeline.py": "import json\nfrom typing import Any\n\ndef parse(raw_data: list[str]) -> list[dict[str, Any]]:\n    parsed = []\n    for item in raw_data:\n        if item.startswith('{'):\n            parsed.append(json.loads(item))\n        else:\n            parsed.append({'value': item.strip()})\n    return parsed\n\ndef validate(data: list[dict[str, Any]]) -> list[dict[str, Any]]:\n    return [item for item in data if 'value' in item and item['value']]\n\ndef transform(data: list[dict[str, Any]]) -> list[dict[str, Any]]:\n    return [{k: v.upper() if isinstance(v, str) else v for k, v in item.items()} for item in data]\n\ndef filter_by_config(data: list[dict[str, Any]], config: dict) -> list[dict[str, Any]]:\n    categories = config.get('categories', ['default'])\n    return [item for item in data if item.get('category', 'default') in categories]\n\ndef process_data(raw_data: list[str], config: dict) -> list[dict[str, Any]]:\n    return filter_by_config(transform(validate(parse(raw_data))), config)\n"}},
        tools_required=["edit"],
        max_turns=10,
        verification_script="code=open('pipeline.py').read(); assert 'def parse(' in code and 'def validate(' in code and 'def transform(' in code",
    ),
    Task(
        task_id="edit-018",
        category=TaskCategory.EDIT,
        difficulty=Difficulty.EASY,
        description="Change the variable name 'd' to 'data' for readability",
        initial_state={
            "process.py": "def process(d):\n    return [x * 2 for x in d if x > 0]\n",
        },
        expected_outcome={"files": {"process.py": "def process(data):\n    return [x * 2 for x in data if x > 0]\n"}},
        tools_required=["edit"],
        max_turns=2,
        verification_script="code=open('process.py').read(); assert 'data' in code",
    ),
    Task(
        task_id="edit-019",
        category=TaskCategory.EDIT,
        difficulty=Difficulty.MEDIUM,
        description="Add unit tests for the Calculator class",
        initial_state={
            "calc.py": "class Calculator:\n    def add(self, a, b):\n        return a + b\n\n    def divide(self, a, b):\n        if b == 0:\n            raise ValueError('Division by zero')\n        return a / b\n",
        },
        expected_outcome={"file_exists": ["test_calc.py"]},
        tools_required=["edit", "write"],
        max_turns=5,
        verification_script="import os; assert os.path.exists('test_calc.py')",
    ),
    Task(
        task_id="edit-020",
        category=TaskCategory.EDIT,
        difficulty=Difficulty.HARD,
        description="Convert the synchronous file processing pipeline to use asyncio with aiofiles",
        initial_state={
            "pipeline.py": "def read_file(path):\n    with open(path) as f:\n        return f.read()\n\ndef process_text(text):\n    return text.upper()\n\ndef write_file(path, content):\n    with open(path, 'w') as f:\n        f.write(content)\n\ndef main(input_path, output_path):\n    text = read_file(input_path)\n    result = process_text(text)\n    write_file(output_path, result)\n",
        },
        expected_outcome={"files": {"pipeline.py": "import asyncio\nimport aiofiles\n\nasync def read_file(path):\n    async with aiofiles.open(path) as f:\n        return await f.read()\n\ndef process_text(text):\n    return text.upper()\n\nasync def write_file(path, content):\n    async with aiofiles.open(path, 'w') as f:\n        await f.write(content)\n\nasync def main(input_path, output_path):\n    text = await read_file(input_path)\n    result = process_text(text)\n    await write_file(output_path, result)\n"}},
        tools_required=["edit"],
        max_turns=8,
        verification_script="code=open('pipeline.py').read(); assert 'async' in code and 'await' in code",
    ),
    Task(
        task_id="edit-021",
        category=TaskCategory.EDIT,
        difficulty=Difficulty.EASY,
        description="Remove the deprecated function and all references to it",
        initial_state={
            "api.py": "def old_endpoint():\n    pass\n\ndef new_endpoint():\n    return 'ok'\n\ndef handler():\n    old_endpoint()\n    new_endpoint()\n",
        },
        expected_outcome={"files": {"api.py": "def new_endpoint():\n    return 'ok'\n\ndef handler():\n    new_endpoint()\n"}},
        tools_required=["edit"],
        max_turns=3,
        verification_script="code=open('api.py').read(); assert 'old_endpoint' not in code",
    ),
    Task(
        task_id="edit-022",
        category=TaskCategory.EDIT,
        difficulty=Difficulty.MEDIUM,
        description="Add a retry decorator that retries the decorated function up to 3 times on any exception",
        initial_state={
            "retry.py": "import time\nimport functools\n",
        },
        expected_outcome={"files": {"retry.py": "import time\nimport functools\n\ndef retry(max_attempts=3, delay=1):\n    def decorator(func):\n        @functools.wraps(func)\n        def wrapper(*args, **kwargs):\n            for attempt in range(max_attempts):\n                try:\n                    return func(*args, **kwargs)\n                except Exception:\n                    if attempt == max_attempts - 1:\n                        raise\n                    time.sleep(delay)\n        return wrapper\n    return decorator\n"}},
        tools_required=["edit"],
        max_turns=8,
        verification_script="code=open('retry.py').read(); assert 'retry' in code and 'decorator' in code",
    ),
]

# ── READ TASKS (16 tasks) ────────────────────────────────────────────

READ_TASKS: list[Task] = [
    Task(
        task_id="read-001",
        category=TaskCategory.READ,
        difficulty=Difficulty.EASY,
        description="What is the value of the MAX_RETRIES constant?",
        initial_state={
            "config.py": "MAX_RETRIES = 3\nTIMEOUT = 30\nHOST = 'localhost'\n",
        },
        expected_outcome={"stdout_contains": ["3"]},
        tools_required=["read"],
        max_turns=2,
        verification_script="pass",
    ),
    Task(
        task_id="read-002",
        category=TaskCategory.READ,
        difficulty=Difficulty.EASY,
        description="List all function names defined in the module",
        initial_state={
            "utils.py": "def add(a, b):\n    return a + b\n\ndef subtract(a, b):\n    return a - b\n\ndef multiply(a, b):\n    return a * b\n\nclass Calculator:\n    def compute(self):\n        pass\n",
        },
        expected_outcome={"stdout_contains": ["add", "subtract", "multiply"]},
        tools_required=["read"],
        max_turns=2,
        verification_script="pass",
    ),
    Task(
        task_id="read-003",
        category=TaskCategory.READ,
        difficulty=Difficulty.MEDIUM,
        description="Find which function calls the external API and what URL it uses",
        initial_state={
            "api.py": "import requests\n\nBASE_URL = 'https://api.example.com'\n\ndef get_user(user_id):\n    return requests.get(f'{BASE_URL}/users/{user_id}').json()\n\ndef create_user(data):\n    return requests.post(f'{BASE_URL}/users', json=data).json()\n\ndef health_check():\n    return requests.get(f'{BASE_URL}/health').status_code == 200\n",
        },
        expected_outcome={"stdout_contains": ["api.example.com"]},
        tools_required=["read"],
        max_turns=3,
        verification_script="pass",
    ),
    Task(
        task_id="read-004",
        category=TaskCategory.READ,
        difficulty=Difficulty.MEDIUM,
        description="Trace the call graph: what functions does process_order() call?",
        initial_state={
            "orders.py": "def validate(data):\n    return bool(data.get('id'))\n\ndef enrich(data):\n    data['timestamp'] = 'now'\n    return data\n\ndef save(data):\n    print(f'Saved {data}')\n    return True\n\ndef notify(data):\n    print(f'Notified for {data[\"id\"]}')\n\ndef process_order(order):\n    if validate(order):\n        enriched = enrich(order)\n        save(enriched)\n        notify(enriched)\n        return enriched\n    return None\n",
        },
        expected_outcome={"stdout_contains": ["validate", "enrich", "save", "notify"]},
        tools_required=["read"],
        max_turns=5,
        verification_script="pass",
    ),
    Task(
        task_id="read-005",
        category=TaskCategory.READ,
        difficulty=Difficulty.EASY,
        description="What are the imports in this file?",
        initial_state={
            "app.py": "import os\nimport sys\nfrom pathlib import Path\nfrom collections import defaultdict\n",
        },
        expected_outcome={"stdout_contains": ["os", "sys", "Path", "defaultdict"]},
        tools_required=["read"],
        max_turns=2,
        verification_script="pass",
    ),
    Task(
        task_id="read-006",
        category=TaskCategory.READ,
        difficulty=Difficulty.HARD,
        description="Identify all potential race conditions in the codebase and explain the fix",
        initial_state={
            "cache.py": "cache = {}\n\ndef get(key):\n    return cache.get(key)\n\ndef set(key, value):\n    cache[key] = value\n\ndef get_or_set(key, default):\n    if key not in cache:\n        cache[key] = default\n    return cache[key]\n",
        },
        expected_outcome={"stdout_contains": ["race", "get_or_set"]},
        tools_required=["read"],
        max_turns=5,
        verification_script="pass",
    ),
    Task(
        task_id="read-007",
        category=TaskCategory.READ,
        difficulty=Difficulty.MEDIUM,
        description="What is the inheritance hierarchy of the classes?",
        initial_state={
            "models.py": "class Animal:\n    pass\n\nclass Mammal(Animal):\n    pass\n\nclass Dog(Mammal):\n    pass\n\nclass Cat(Mammal):\n    pass\n\nclass Bird(Animal):\n    pass\n",
        },
        expected_outcome={"stdout_contains": ["Dog", "Mammal", "Animal"]},
        tools_required=["read"],
        max_turns=3,
        verification_script="pass",
    ),
    Task(
        task_id="read-008",
        category=TaskCategory.READ,
        difficulty=Difficulty.MEDIUM,
        description="Find all TODO comments in the codebase and list them with file and line numbers",
        initial_state={
            "main.py": "# TODO: add error handling\nimport os\n\ndef run():\n    # TODO: implement\n    pass\n",
            "utils.py": "# TODO: optimize this\ndef helper():\n    pass\n",
        },
        expected_outcome={"stdout_contains": ["TODO"]},
        tools_required=["read"],
        max_turns=3,
        verification_script="pass",
    ),
    Task(
        task_id="read-009",
        category=TaskCategory.READ,
        difficulty=Difficulty.HARD,
        description="Find the security vulnerability in the SQL query construction and explain the fix",
        initial_state={
            "db.py": "def get_user(cursor, username):\n    query = f\"SELECT * FROM users WHERE username = '{username}'\"\n    cursor.execute(query)\n    return cursor.fetchone()\n",
        },
        expected_outcome={"stdout_contains": ["SQL", "injection", "parameterized"]},
        tools_required=["read"],
        max_turns=5,
        verification_script="pass",
    ),
    Task(
        task_id="read-010",
        category=TaskCategory.READ,
        difficulty=Difficulty.EASY,
        description="What environment variables does the configuration module expect?",
        initial_state={
            "config.py": "import os\n\nDATABASE_URL = os.getenv('DATABASE_URL', 'sqlite:///default.db')\nREDIS_URL = os.getenv('REDIS_URL', 'redis://localhost:6379')\nSECRET_KEY = os.getenv('SECRET_KEY')\nDEBUG = os.getenv('DEBUG', 'false').lower() == 'true'\n",
        },
        expected_outcome={"stdout_contains": ["DATABASE_URL", "REDIS_URL", "SECRET_KEY", "DEBUG"]},
        tools_required=["read"],
        max_turns=2,
        verification_script="pass",
    ),
    Task(
        task_id="read-011",
        category=TaskCategory.READ,
        difficulty=Difficulty.MEDIUM,
        description="Determine which decorator is applied to which function and in what order",
        initial_state={
            "views.py": "import functools\n\ndef admin_required(func):\n    @functools.wraps(func)\n    def wrapper(*args, **kwargs):\n        return func(*args, **kwargs)\n    return wrapper\n\ndef login_required(func):\n    @functools.wraps(func)\n    def wrapper(*args, **kwargs):\n        return func(*args, **kwargs)\n    return wrapper\n\n@admin_required\n@login_required\ndef dashboard():\n    return 'dashboard'\n",
        },
        expected_outcome={"stdout_contains": ["admin_required", "login_required", "dashboard"]},
        tools_required=["read"],
        max_turns=3,
        verification_script="pass",
    ),
    Task(
        task_id="read-012",
        category=TaskCategory.READ,
        difficulty=Difficulty.HARD,
        description="Explain the control flow when process_payment is called with an expired card",
        initial_state={
            "payment.py": "class PaymentError(Exception):\n    pass\n\nclass CardExpiredError(PaymentError):\n    pass\n\nclass InsufficientFundsError(PaymentError):\n    pass\n\ndef validate_card(card):\n    if card.get('expired'):\n        raise CardExpiredError('Card expired')\n    return True\n\ndef charge(card, amount):\n    if card.get('balance', 0) < amount:\n        raise InsufficientFundsError('Insufficient funds')\n    card['balance'] = card.get('balance', 0) - amount\n    return {'status': 'success', 'amount': amount}\n\ndef process_payment(card, amount):\n    try:\n        validate_card(card)\n        result = charge(card, amount)\n        return result\n    except CardExpiredError:\n        return {'status': 'failed', 'reason': 'card_expired'}\n    except InsufficientFundsError:\n        return {'status': 'failed', 'reason': 'insufficient_funds'}\n    except PaymentError:\n        return {'status': 'failed', 'reason': 'unknown'}\n",
        },
        expected_outcome={"stdout_contains": ["CardExpiredError", "failed", "card_expired"]},
        tools_required=["read"],
        max_turns=5,
        verification_script="pass",
    ),
    Task(
        task_id="read-013",
        category=TaskCategory.READ,
        difficulty=Difficulty.EASY,
        description="How many classes are defined in the file?",
        initial_state={
            "shapes.py": "class Circle:\n    pass\n\nclass Square:\n    pass\n\nclass Triangle:\n    pass\n",
        },
        expected_outcome={"stdout_contains": ["3"]},
        tools_required=["read"],
        max_turns=2,
        verification_script="pass",
    ),
    Task(
        task_id="read-014",
        category=TaskCategory.READ,
        difficulty=Difficulty.MEDIUM,
        description="Find all hardcoded configuration values that should be environment variables",
        initial_state={
            "app.py": "DATABASE_URL = 'postgresql://localhost:5432/mydb'\nAPI_KEY = 'sk-1234567890abcdef'\nDEBUG = True\nPORT = 8080\nTIMEOUT = 30\nMAX_CONNECTIONS = 100\n",
        },
        expected_outcome={"stdout_contains": ["DATABASE_URL", "API_KEY"]},
        tools_required=["read"],
        max_turns=3,
        verification_script="pass",
    ),
    Task(
        task_id="read-015",
        category=TaskCategory.READ,
        difficulty=Difficulty.HARD,
        description="Find all circular import dependencies across the modules",
        initial_state={
            "a.py": "from b import B\n\nclass A:\n    def use_b(self):\n        return B()\n",
            "b.py": "from c import C\n\nclass B:\n    def use_c(self):\n        return C()\n",
            "c.py": "from a import A\n\nclass C:\n    def use_a(self):\n        return A()\n",
        },
        expected_outcome={"stdout_contains": ["circular"]},
        tools_required=["read"],
        max_turns=5,
        verification_script="pass",
    ),
    Task(
        task_id="read-016",
        category=TaskCategory.READ,
        difficulty=Difficulty.MEDIUM,
        description="Identify the design pattern used and explain its purpose",
        initial_state={
            "factory.py": "class Animal:\n    def speak(self):\n        raise NotImplementedError\n\nclass Dog(Animal):\n    def speak(self):\n        return 'Woof'\n\nclass Cat(Animal):\n    def speak(self):\n        return 'Meow'\n\nclass AnimalFactory:\n    @staticmethod\n    def create(animal_type):\n        if animal_type == 'dog':\n            return Dog()\n        elif animal_type == 'cat':\n            return Cat()\n        raise ValueError(f'Unknown animal: {animal_type}')\n",
        },
        expected_outcome={"stdout_contains": ["Factory", "pattern"]},
        tools_required=["read"],
        max_turns=3,
        verification_script="pass",
    ),
]

# ── WRITE TASKS (16 tasks) ───────────────────────────────────────────

WRITE_TASKS: list[Task] = [
    Task(
        task_id="write-001",
        category=TaskCategory.WRITE,
        difficulty=Difficulty.EASY,
        description="Create a Python module with a function that reverses a string",
        initial_state={},
        expected_outcome={"file_exists": ["string_utils.py"]},
        tools_required=["write"],
        max_turns=3,
        verification_script="import importlib; mod=importlib.import_module('string_utils'); assert mod.reverse_string('hello') == 'olleh'",
    ),
    Task(
        task_id="write-002",
        category=TaskCategory.WRITE,
        difficulty=Difficulty.MEDIUM,
        description="Create a configuration file for a Flask application with development, testing, and production settings",
        initial_state={},
        expected_outcome={"file_exists": ["config.py"]},
        tools_required=["write"],
        max_turns=5,
        verification_script="import os; assert os.path.exists('config.py')",
    ),
    Task(
        task_id="write-003",
        category=TaskCategory.WRITE,
        difficulty=Difficulty.MEDIUM,
        description="Write unit tests for a given calculator module",
        initial_state={
            "calculator.py": "class Calculator:\n    def add(self, a, b):\n        return a + b\n\n    def subtract(self, a, b):\n        return a - b\n\n    def multiply(self, a, b):\n        return a * b\n\n    def divide(self, a, b):\n        if b == 0:\n            raise ValueError('Cannot divide by zero')\n        return a / b\n",
        },
        expected_outcome={"file_exists": ["test_calculator.py"]},
        tools_required=["write"],
        max_turns=5,
        verification_script="import os; assert os.path.exists('test_calculator.py')",
    ),
    Task(
        task_id="write-004",
        category=TaskCategory.WRITE,
        difficulty=Difficulty.EASY,
        description="Create a .gitignore file for a Python project",
        initial_state={},
        expected_outcome={"file_exists": [".gitignore"]},
        tools_required=["write"],
        max_turns=2,
        verification_script="import os; assert os.path.exists('.gitignore')",
    ),
    Task(
        task_id="write-005",
        category=TaskCategory.WRITE,
        difficulty=Difficulty.HARD,
        description="Create a Dockerfile for a Python FastAPI application with multi-stage build",
        initial_state={
            "requirements.txt": "fastapi==0.104.1\nuvicorn==0.24.0\npydantic==2.5.0\n",
        },
        expected_outcome={"file_exists": ["Dockerfile"]},
        tools_required=["write"],
        max_turns=5,
        verification_script="import os; assert os.path.exists('Dockerfile')",
    ),
    Task(
        task_id="write-006",
        category=TaskCategory.WRITE,
        difficulty=Difficulty.MEDIUM,
        description="Create a Pydantic model for a User with name, email, age, and address fields with proper validation",
        initial_state={},
        expected_outcome={"file_exists": ["models.py"]},
        tools_required=["write"],
        max_turns=5,
        verification_script="import os; assert os.path.exists('models.py')",
    ),
    Task(
        task_id="write-007",
        category=TaskCategory.WRITE,
        difficulty=Difficulty.MEDIUM,
        description="Write a CI configuration file (GitHub Actions) that runs Python tests on push",
        initial_state={},
        expected_outcome={"file_exists": [".github/workflows/ci.yml"]},
        tools_required=["write"],
        max_turns=5,
        verification_script="import os; assert os.path.exists('.github/workflows/ci.yml')",
    ),
    Task(
        task_id="write-008",
        category=TaskCategory.WRITE,
        difficulty=Difficulty.HARD,
        description="Create a complete Python package structure with __init__.py, module files, and setup",
        initial_state={},
        expected_outcome={"file_exists": ["mylib/__init__.py", "mylib/core.py", "mylib/utils.py", "setup.py"]},
        tools_required=["write"],
        max_turns=8,
        verification_script="import os; assert all(os.path.exists(f) for f in ['mylib/__init__.py', 'mylib/core.py', 'mylib/utils.py', 'setup.py'])",
    ),
    Task(
        task_id="write-009",
        category=TaskCategory.WRITE,
        difficulty=Difficulty.EASY,
        description="Create a JSON config file for a logging setup with console and file handlers",
        initial_state={},
        expected_outcome={"file_exists": ["logging_config.json"]},
        tools_required=["write"],
        max_turns=3,
        verification_script="import os; assert os.path.exists('logging_config.json')",
    ),
    Task(
        task_id="write-010",
        category=TaskCategory.WRITE,
        difficulty=Difficulty.HARD,
        description="Write a complete REST API client module with GET, POST, PUT, DELETE methods, error handling, and retry logic",
        initial_state={},
        expected_outcome={"file_exists": ["api_client.py"]},
        tools_required=["write"],
        max_turns=8,
        verification_script="import os; assert os.path.exists('api_client.py')",
    ),
    Task(
        task_id="write-011",
        category=TaskCategory.WRITE,
        difficulty=Difficulty.MEDIUM,
        description="Write a pytest conftest.py with fixtures for a test database and mock HTTP client",
        initial_state={},
        expected_outcome={"file_exists": ["conftest.py"]},
        tools_required=["write"],
        max_turns=5,
        verification_script="import os; assert os.path.exists('conftest.py')",
    ),
    Task(
        task_id="write-012",
        category=TaskCategory.WRITE,
        difficulty=Difficulty.EASY,
        description="Create a Makefile with targets for: install, test, lint, clean, and run",
        initial_state={},
        expected_outcome={"file_exists": ["Makefile"]},
        tools_required=["write"],
        max_turns=3,
        verification_script="import os; assert os.path.exists('Makefile')",
    ),
    Task(
        task_id="write-013",
        category=TaskCategory.WRITE,
        difficulty=Difficulty.HARD,
        description="Create a Python CLI tool using argparse that supports subcommands: add, list, delete for a todo app",
        initial_state={},
        expected_outcome={"file_exists": ["todo_cli.py"]},
        tools_required=["write"],
        max_turns=8,
        verification_script="import os; assert os.path.exists('todo_cli.py')",
    ),
    Task(
        task_id="write-014",
        category=TaskCategory.WRITE,
        difficulty=Difficulty.MEDIUM,
        description="Write SQL migration files for creating a users table with proper indexes and constraints",
        initial_state={},
        expected_outcome={"file_exists": ["migrations/001_create_users.sql"]},
        tools_required=["write"],
        max_turns=5,
        verification_script="import os; assert os.path.exists('migrations/001_create_users.sql')",
    ),
    Task(
        task_id="write-015",
        category=TaskCategory.WRITE,
        difficulty=Difficulty.MEDIUM,
        description="Create a docker-compose.yml for a web app with PostgreSQL and Redis services",
        initial_state={},
        expected_outcome={"file_exists": ["docker-compose.yml"]},
        tools_required=["write"],
        max_turns=5,
        verification_script="import os; assert os.path.exists('docker-compose.yml')",
    ),
    Task(
        task_id="write-016",
        category=TaskCategory.WRITE,
        difficulty=Difficulty.HARD,
        description="Create a comprehensive Python logging module with structured JSON output, rotation, and custom formatters",
        initial_state={},
        expected_outcome={"file_exists": ["logger.py"]},
        tools_required=["write"],
        max_turns=8,
        verification_script="import os; assert os.path.exists('logger.py')",
    ),
]

# ── MULTI-TOOL TASKS (16 tasks) ─────────────────────────────────────

MULTI_TOOL_TASKS: list[Task] = [
    Task(
        task_id="multi-001",
        category=TaskCategory.MULTI_TOOL,
        difficulty=Difficulty.HARD,
        description="Find all Python files with syntax errors, fix them, and verify the fixes work",
        initial_state={
            "module1.py": "def foo():\n    return 'hello\n",
            "module2.py": "def bar():\n    return 'world'\n",
            "module3.py": "class Baz:\n    def __init__(self\n        self.value = 1\n",
        },
        expected_outcome={"files": {"module2.py": "def bar():\n    return 'world'\n"}},
        tools_required=["read", "bash", "edit"],
        max_turns=10,
        verification_script="import py_compile; [py_compile.compile(f, doraise=True) for f in ['module1.py', 'module2.py', 'module3.py']]",
    ),
    Task(
        task_id="multi-002",
        category=TaskCategory.MULTI_TOOL,
        difficulty=Difficulty.HARD,
        description="Read the requirements file, create the project structure, and write initial code for all modules",
        initial_state={
            "REQUIREMENTS.md": "# Project: Task Manager\n\nModules needed:\n- models.py: Task and User dataclasses\n- storage.py: File-based persistence\n- api.py: REST API endpoints\n- cli.py: Command-line interface\n",
        },
        expected_outcome={"file_exists": ["models.py", "storage.py", "api.py", "cli.py"]},
        tools_required=["read", "write"],
        max_turns=10,
        verification_script="import os; assert all(os.path.exists(f) for f in ['models.py', 'storage.py', 'api.py', 'cli.py'])",
    ),
    Task(
        task_id="multi-003",
        category=TaskCategory.MULTI_TOOL,
        difficulty=Difficulty.MEDIUM,
        description="Refactor the monolith into separate modules, update imports in all files",
        initial_state={
            "monolith.py": "class User:\n    def __init__(self, name, email):\n        self.name = name\n        self.email = email\n\nclass UserManager:\n    users = []\n    def add(self, user):\n        self.users.append(user)\n    def find(self, name):\n        return next((u for u in self.users if u.name == name), None)\n\ndef send_email(to, subject, body):\n    return {'to': to, 'subject': subject, 'body': body}\n\ndef format_user(user):\n    return f'{user.name} ({user.email})'\n",
            "main.py": "from monolith import User, UserManager, send_email, format_user\n\nmgr = UserManager()\nmgr.add(User('Alice', 'alice@test.com'))\nprint(format_user(mgr.find('Alice')))\n",
        },
        expected_outcome={"file_exists": ["models.py", "manager.py", "email.py", "format.py"]},
        tools_required=["read", "write", "edit"],
        max_turns=12,
        verification_script="import os; assert all(os.path.exists(f) for f in ['models.py', 'manager.py', 'email.py', 'format.py'])",
    ),
    Task(
        task_id="multi-004",
        category=TaskCategory.MULTI_TOOL,
        difficulty=Difficulty.HARD,
        description="Read the existing test file, understand the module being tested, add missing test cases, and run the tests",
        initial_state={
            "math_ops.py": "def add(a, b):\n    return a + b\n\ndef subtract(a, b):\n    return a - b\n\ndef multiply(a, b):\n    return a * b\n\ndef divide(a, b):\n    if b == 0:\n        raise ValueError('Division by zero')\n    return a / b\n",
            "test_math_ops.py": "import pytest\nfrom math_ops import add, subtract\n\ndef test_add():\n    assert add(2, 3) == 5\n\ndef test_subtract():\n    assert subtract(5, 3) == 2\n",
        },
        expected_outcome={"file_exists": ["test_math_ops.py"]},
        tools_required=["read", "edit", "bash"],
        max_turns=8,
        verification_script="import os; code=open('test_math_ops.py').read(); assert 'multiply' in code or 'divide' in code",
    ),
    Task(
        task_id="multi-005",
        category=TaskCategory.MULTI_TOOL,
        difficulty=Difficulty.MEDIUM,
        description="Extract all hardcoded strings from the Python files into a constants file and update references",
        initial_state={
            "app.py": "DB_HOST = 'localhost'\nDB_PORT = 5432\nAPI_URL = 'https://api.example.com'\n\ndef connect():\n    return f'Connecting to {DB_HOST}:{DB_PORT}'\n\ndef fetch():\n    return f'Fetching from {API_URL}'\n",
        },
        expected_outcome={"file_exists": ["constants.py"]},
        tools_required=["read", "write", "edit"],
        max_turns=8,
        verification_script="import os; assert os.path.exists('constants.py')",
    ),
    Task(
        task_id="multi-006",
        category=TaskCategory.MULTI_TOOL,
        difficulty=Difficulty.HARD,
        description="Set up a complete Python project with proper structure, configuration, and tests",
        initial_state={},
        expected_outcome={"file_exists": ["pyproject.toml", "src/myapp/__init__.py", "src/myapp/main.py", "tests/__init__.py", "tests/test_main.py"]},
        tools_required=["write", "bash"],
        max_turns=10,
        verification_script="import os; assert all(os.path.exists(f) for f in ['pyproject.toml', 'src/myapp/__init__.py', 'src/myapp/main.py'])",
    ),
    Task(
        task_id="multi-007",
        category=TaskCategory.MULTI_TOOL,
        difficulty=Difficulty.MEDIUM,
        description="Read the CSV data, write a Python script to analyze it, and run the analysis",
        initial_state={
            "sales.csv": "product,quantity,price\nWidget A,100,9.99\nWidget B,50,19.99\nWidget C,75,14.99\nWidget D,200,4.99\n",
        },
        expected_outcome={"file_exists": ["analyze.py"]},
        tools_required=["read", "write", "bash"],
        max_turns=8,
        verification_script="import os; assert os.path.exists('analyze.py')",
    ),
    Task(
        task_id="multi-008",
        category=TaskCategory.MULTI_TOOL,
        difficulty=Difficulty.HARD,
        description="Find and fix the bug in the authentication module, then add comprehensive tests",
        initial_state={
            "auth.py": "import hashlib\n\ndef hash_password(password):\n    return hashlib.md5(password.encode()).hexdigest()\n\ndef verify_password(password, hashed):\n    return hash_password(password) == hashed\n\ndef authenticate(username, password, users):\n    user = users.get(username)\n    if user and verify_password(password, user['password_hash']):\n        return True\n    return False\n",
            "test_auth.py": "from auth import hash_password, verify_password\n\ndef test_hash():\n    assert hash_password('test') == hash_password('test')\n",
        },
        expected_outcome={"file_exists": ["test_auth.py"]},
        tools_required=["read", "edit", "write", "bash"],
        max_turns=10,
        verification_script="code=open('auth.py').read(); assert 'sha256' in code or 'sha' in code",
    ),
    Task(
        task_id="multi-009",
        category=TaskCategory.MULTI_TOOL,
        difficulty=Difficulty.MEDIUM,
        description="Convert a YAML configuration to environment variable format and create a .env file",
        initial_state={
            "config.yaml": "database:\n  host: localhost\n  port: 5432\n  name: myapp\nserver:\n  host: 0.0.0.0\n  port: 8000\nlogging:\n  level: INFO\n  file: app.log\n",
        },
        expected_outcome={"file_exists": [".env"]},
        tools_required=["read", "write"],
        max_turns=5,
        verification_script="import os; assert os.path.exists('.env')",
    ),
    Task(
        task_id="multi-010",
        category=TaskCategory.MULTI_TOOL,
        difficulty=Difficulty.HARD,
        description="Write a migration script to refactor the database schema and update the ORM models accordingly",
        initial_state={
            "models.py": "from sqlalchemy import Column, Integer, String\nfrom sqlalchemy.ext.declarative import declarative_base\n\nBase = declarative_base()\n\nclass User(Base):\n    __tablename__ = 'users'\n    id = Column(Integer, primary_key=True)\n    name = Column(String)\n    email = Column(String)\n",
        },
        expected_outcome={"file_exists": ["migration.py", "models.py"]},
        tools_required=["read", "edit", "write"],
        max_turns=10,
        verification_script="import os; assert os.path.exists('migration.py')",
    ),
    Task(
        task_id="multi-011",
        category=TaskCategory.MULTI_TOOL,
        difficulty=Difficulty.MEDIUM,
        description="Create a Python package from scratch with proper typing, docstrings, and a comprehensive test suite",
        initial_state={},
        expected_outcome={"file_exists": ["stringproc/__init__.py", "stringproc/core.py", "tests/test_core.py"]},
        tools_required=["write", "bash"],
        max_turns=10,
        verification_script="import os; assert all(os.path.exists(f) for f in ['stringproc/__init__.py', 'stringproc/core.py', 'tests/test_core.py'])",
    ),
    Task(
        task_id="multi-012",
        category=TaskCategory.MULTI_TOOL,
        difficulty=Difficulty.HARD,
        description="Analyze the codebase for issues, create a bug report, fix the bugs, and verify the fixes",
        initial_state={
            "calculator.py": "def add(a, b):\n    return a + b\n\ndef divide(a, b):\n    return a / b\n\ndef calculate(op, *args):\n    if op == 'add':\n        return add(*args)\n    elif op == 'divide':\n        return divide(*args)\n",
        },
        expected_outcome={"file_exists": ["calculator.py", "BUG_REPORT.md"]},
        tools_required=["read", "edit", "write", "bash"],
        max_turns=10,
        verification_script="import os; assert os.path.exists('BUG_REPORT.md')",
    ),
    Task(
        task_id="multi-013",
        category=TaskCategory.MULTI_TOOL,
        difficulty=Difficulty.MEDIUM,
        description="Read the API specification and implement the endpoints with proper error handling",
        initial_state={
            "api_spec.md": "# API Specification\n\n## Endpoints\n\n### GET /users\nReturns list of all users\n\n### GET /users/{id}\nReturns a single user by ID\n\n### POST /users\nCreates a new user\n\n### DELETE /users/{id}\nDeletes a user by ID\n",
        },
        expected_outcome={"file_exists": ["api.py"]},
        tools_required=["read", "write"],
        max_turns=10,
        verification_script="import os; assert os.path.exists('api.py')",
    ),
    Task(
        task_id="multi-014",
        category=TaskCategory.MULTI_TOOL,
        difficulty=Difficulty.HARD,
        description="Set up a complete development environment: create virtual env, install dependencies, run linting and tests",
        initial_state={
            "requirements.txt": "pydantic>=2.0\nrich>=13.0\n",
            "app.py": "from pydantic import BaseModel\n\nclass Item(BaseModel):\n    name: str\n    price: float\n\nprint('App loaded successfully')\n",
        },
        expected_outcome={"exit_code": 0},
        tools_required=["bash", "write"],
        max_turns=8,
        verification_script="pass",
    ),
    Task(
        task_id="multi-015",
        category=TaskCategory.MULTI_TOOL,
        difficulty=Difficulty.HARD,
        description="Implement a caching decorator with TTL, write tests, and ensure 80%+ code coverage",
        initial_state={},
        expected_outcome={"file_exists": ["cache_decorator.py", "test_cache_decorator.py"]},
        tools_required=["write", "bash"],
        max_turns=10,
        verification_script="import os; assert all(os.path.exists(f) for f in ['cache_decorator.py', 'test_cache_decorator.py'])",
    ),
    Task(
        task_id="multi-016",
        category=TaskCategory.MULTI_TOOL,
        difficulty=Difficulty.MEDIUM,
        description="Read the existing module, create a type stub file (.pyi), and verify type checking works",
        initial_state={
            "library.py": "def process(data: list, key: str = 'id') -> dict:\n    return {item[key]: item for item in data}\n\ndef transform(value: int, scale: float = 1.0) -> float:\n    return value * scale\n\nclass Handler:\n    def __init__(self, name: str) -> None:\n        self.name = name\n\n    def handle(self, data: bytes) -> str:\n        return data.decode()\n",
        },
        expected_outcome={"file_exists": ["library.pyi"]},
        tools_required=["read", "write"],
        max_turns=6,
        verification_script="import os; assert os.path.exists('library.pyi')",
    ),
]

# ── ERROR RECOVERY TASKS (16 tasks) ─────────────────────────────────

ERROR_RECOVERY_TASKS: list[Task] = [
    Task(
        task_id="error-001",
        category=TaskCategory.ERROR_RECOVERY,
        difficulty=Difficulty.EASY,
        description="Fix the indentation error that causes a syntax error",
        initial_state={
            "broken.py": "def greet(name):\n    message = 'Hello, ' + name\n  return message\n",
        },
        expected_outcome={"files": {"broken.py": "def greet(name):\n    message = 'Hello, ' + name\n    return message\n"}},
        tools_required=["read", "edit"],
        max_turns=3,
        verification_script="import py_compile; py_compile.compile('broken.py', doraise=True)",
    ),
    Task(
        task_id="error-002",
        category=TaskCategory.ERROR_RECOVERY,
        difficulty=Difficulty.EASY,
        description="Fix the NameError: the variable 'data' is not defined",
        initial_state={
            "broken.py": "def process():\n    return data['key']\n",
        },
        expected_outcome={"files": {"broken.py": "def process(data):\n    return data['key']\n"}},
        tools_required=["read", "edit"],
        max_turns=3,
        verification_script="code=open('broken.py').read(); assert 'def process(data)' in code",
    ),
    Task(
        task_id="error-003",
        category=TaskCategory.ERROR_RECOVERY,
        difficulty=Difficulty.MEDIUM,
        description="Fix the RuntimeError: the recursive function has no base case and will stack overflow",
        initial_state={
            "broken.py": "def fibonacci(n):\n    return fibonacci(n - 1) + fibonacci(n - 2)\n",
        },
        expected_outcome={"files": {"broken.py": "def fibonacci(n):\n    if n <= 1:\n        return n\n    return fibonacci(n - 1) + fibonacci(n - 2)\n"}},
        tools_required=["read", "edit"],
        max_turns=3,
        verification_script="code=open('broken.py').read(); assert 'if' in code",
    ),
    Task(
        task_id="error-004",
        category=TaskCategory.ERROR_RECOVERY,
        difficulty=Difficulty.MEDIUM,
        description="Fix the import error and make the module work without the missing dependency",
        initial_state={
            "broken.py": "from nonexistent_module import Something\n\ndef run():\n    obj = Something()\n    return obj.process()\n",
        },
        expected_outcome={"files": {"broken.py": "try:\n    from nonexistent_module import Something\nexcept ImportError:\n    class Something:\n        def process(self):\n            return 'fallback'\n\ndef run():\n    obj = Something()\n    return obj.process()\n"}},
        tools_required=["read", "edit"],
        max_turns=5,
        verification_script="code=open('broken.py').read(); assert 'try' in code or 'ImportError' in code",
    ),
    Task(
        task_id="error-005",
        category=TaskCategory.ERROR_RECOVERY,
        difficulty=Difficulty.HARD,
        description="Fix a race condition in the Singleton implementation",
        initial_state={
            "broken.py": "class Singleton:\n    _instance = None\n\n    def __new__(cls):\n        if cls._instance is None:\n            cls._instance = super().__new__(cls)\n        return cls._instance\n",
        },
        expected_outcome={"files": {"broken.py": "import threading\n\nclass Singleton:\n    _instance = None\n    _lock = threading.Lock()\n\n    def __new__(cls):\n        with cls._lock:\n            if cls._instance is None:\n                cls._instance = super().__new__(cls)\n        return cls._instance\n"}},
        tools_required=["read", "edit"],
        max_turns=5,
        verification_script="code=open('broken.py').read(); assert 'threading' in code or 'Lock' in code",
    ),
    Task(
        task_id="error-006",
        category=TaskCategory.ERROR_RECOVERY,
        difficulty=Difficulty.MEDIUM,
        description="Fix the off-by-one error in the binary search implementation",
        initial_state={
            "broken.py": "def binary_search(arr, target):\n    left, right = 0, len(arr)\n    while left < right:\n        mid = (left + right) // 2\n        if arr[mid] < target:\n            left = mid\n        else:\n            right = mid\n    return left\n",
        },
        expected_outcome={"files": {"broken.py": "def binary_search(arr, target):\n    left, right = 0, len(arr) - 1\n    while left <= right:\n        mid = (left + right) // 2\n        if arr[mid] == target:\n            return mid\n        elif arr[mid] < target:\n            left = mid + 1\n        else:\n            right = mid - 1\n    return -1\n"}},
        tools_required=["read", "edit"],
        max_turns=5,
        verification_script="code=open('broken.py').read(); assert '-1' in code or 'mid + 1' in code",
    ),
    Task(
        task_id="error-007",
        category=TaskCategory.ERROR_RECOVERY,
        difficulty=Difficulty.EASY,
        description="Fix the TypeError: cannot concatenate str and int",
        initial_state={
            "broken.py": "def format_age(name, age):\n    return name + ' is ' + age + ' years old'\n",
        },
        expected_outcome={"files": {"broken.py": "def format_age(name, age):\n    return f'{name} is {age} years old'\n"}},
        tools_required=["read", "edit"],
        max_turns=2,
        verification_script="code=open('broken.py').read(); assert 'f\\'' in code or 'str(age)' in code",
    ),
    Task(
        task_id="error-008",
        category=TaskCategory.ERROR_RECOVERY,
        difficulty=Difficulty.HARD,
        description="Fix the memory leak: the cache grows unbounded",
        initial_state={
            "broken.py": "class Cache:\n    def __init__(self):\n        self._data = {}\n\n    def get(self, key):\n        return self._data.get(key)\n\n    def set(self, key, value):\n        self._data[key] = value\n",
        },
        expected_outcome={"files": {"broken.py": "from collections import OrderedDict\n\nclass Cache:\n    def __init__(self, max_size=1000):\n        self._max_size = max_size\n        self._data = OrderedDict()\n\n    def get(self, key):\n        if key in self._data:\n            self._data.move_to_end(key)\n            return self._data[key]\n        return None\n\n    def set(self, key, value):\n        if key in self._data:\n            self._data.move_to_end(key)\n        else:\n            self._data[key] = value\n            if len(self._data) > self._max_size:\n                self._data.popitem(last=False)\n"}},
        tools_required=["read", "edit"],
        max_turns=8,
        verification_script="code=open('broken.py').read(); assert 'max_size' in code or 'popitem' in code",
    ),
    Task(
        task_id="error-009",
        category=TaskCategory.ERROR_RECOVERY,
        difficulty=Difficulty.MEDIUM,
        description="Fix the KeyError: the code accesses 'user.email' but the dict uses 'mail'",
        initial_state={
            "broken.py": "def get_email(user_dict):\n    return user_dict['email']\n",
        },
        expected_outcome={"files": {"broken.py": "def get_email(user_dict):\n    return user_dict.get('email') or user_dict.get('mail', '')\n"}},
        tools_required=["read", "edit"],
        max_turns=3,
        verification_script="code=open('broken.py').read(); assert 'get(' in code",
    ),
    Task(
        task_id="error-010",
        category=TaskCategory.ERROR_RECOVERY,
        difficulty=Difficulty.HARD,
        description="Fix the SQL injection vulnerability by converting to parameterized queries",
        initial_state={
            "broken.py": "def get_user(cursor, username, password):\n    query = f\"SELECT * FROM users WHERE username='{username}' AND password='{password}'\"\n    cursor.execute(query)\n    return cursor.fetchone()\n",
        },
        expected_outcome={"files": {"broken.py": "def get_user(cursor, username, password):\n    query = \"SELECT * FROM users WHERE username = ? AND password = ?\"\n    cursor.execute(query, (username, password))\n    return cursor.fetchone()\n"}},
        tools_required=["read", "edit"],
        max_turns=5,
        verification_script="code=open('broken.py').read(); assert '?' in code or '%s' not in code",
    ),
    Task(
        task_id="error-011",
        category=TaskCategory.ERROR_RECOVERY,
        difficulty=Difficulty.MEDIUM,
        description="Fix the infinite loop in the while condition",
        initial_state={
            "broken.py": "def count_down(n):\n    while n > 0:\n        print(n)\n    return 'done'\n",
        },
        expected_outcome={"files": {"broken.py": "def count_down(n):\n    while n > 0:\n        print(n)\n        n -= 1\n    return 'done'\n"}},
        tools_required=["read", "edit"],
        max_turns=3,
        verification_script="code=open('broken.py').read(); assert 'n -= 1' in code or 'n = n' in code",
    ),
    Task(
        task_id="error-012",
        category=TaskCategory.ERROR_RECOVERY,
        difficulty=Difficulty.EASY,
        description="Fix the missing colon after the function definition",
        initial_state={
            "broken.py": "def say_hello(name)\n    return f'Hello, {name}!'\n",
        },
        expected_outcome={"files": {"broken.py": "def say_hello(name):\n    return f'Hello, {name}!'\n"}},
        tools_required=["read", "edit"],
        max_turns=2,
        verification_script="code=open('broken.py').read(); assert 'name):' in code",
    ),
    Task(
        task_id="error-013",
        category=TaskCategory.ERROR_RECOVERY,
        difficulty=Difficulty.HARD,
        description="Fix the deadlocks in the banking transfer function and add proper error handling",
        initial_state={
            "broken.py": "import threading\n\nclass Account:\n    def __init__(self, balance):\n        self.balance = balance\n        self.lock = threading.Lock()\n\ndef transfer(from_acc, to_acc, amount):\n    from_acc.lock.acquire()\n    to_acc.lock.acquire()\n    try:\n        from_acc.balance -= amount\n        to_acc.balance += amount\n    finally:\n        from_acc.lock.release()\n        to_acc.lock.release()\n",
        },
        expected_outcome={"files": {"broken.py": "import threading\nimport time\n\nclass Account:\n    def __init__(self, balance):\n        self.balance = balance\n        self.lock = threading.Lock()\n\ndef transfer(from_acc, to_acc, amount):\n    locks = sorted([from_acc.lock, to_acc.lock], key=id)\n    for lock in locks:\n        lock.acquire()\n    try:\n        if from_acc.balance < amount:\n            raise ValueError('Insufficient funds')\n        from_acc.balance -= amount\n        to_acc.balance += amount\n    finally:\n        for lock in locks:\n            lock.release()\n"}},
        tools_required=["read", "edit"],
        max_turns=8,
        verification_script="code=open('broken.py').read(); assert 'sorted' in code or 'Insufficient' in code",
    ),
    Task(
        task_id="error-014",
        category=TaskCategory.ERROR_RECOVERY,
        difficulty=Difficulty.MEDIUM,
        description="Fix the mutable default argument bug",
        initial_state={
            "broken.py": "def add_item(item, items=[]):\n    items.append(item)\n    return items\n",
        },
        expected_outcome={"files": {"broken.py": "def add_item(item, items=None):\n    if items is None:\n        items = []\n    items.append(item)\n    return items\n"}},
        tools_required=["read", "edit"],
        max_turns=3,
        verification_script="code=open('broken.py').read(); assert 'None' in code",
    ),
    Task(
        task_id="error-015",
        category=TaskCategory.ERROR_RECOVERY,
        difficulty=Difficulty.MEDIUM,
        description="Fix the file not found error by adding proper path handling",
        initial_state={
            "broken.py": "def read_config():\n    with open('config.json') as f:\n        import json\n        return json.load(f)\n",
        },
        expected_outcome={"files": {"broken.py": "import json\nfrom pathlib import Path\n\ndef read_config(config_path=None):\n    if config_path is None:\n        config_path = Path(__file__).parent / 'config.json'\n    else:\n        config_path = Path(config_path)\n    if not config_path.exists():\n        return {}\n    with open(config_path) as f:\n        return json.load(f)\n"}},
        tools_required=["read", "edit"],
        max_turns=5,
        verification_script="code=open('broken.py').read(); assert 'Path' in code or 'exists' in code",
    ),
    Task(
        task_id="error-016",
        category=TaskCategory.ERROR_RECOVERY,
        difficulty=Difficulty.HARD,
        description="Add comprehensive error handling to the file processor that currently crashes on any exception",
        initial_state={
            "broken.py": "def process_files(file_paths):\n    results = []\n    for path in file_paths:\n        with open(path) as f:\n            data = f.read()\n            result = data.upper()\n            results.append(result)\n    return results\n",
        },
        expected_outcome={"files": {"broken.py": "import logging\n\nlogger = logging.getLogger(__name__)\n\ndef process_files(file_paths):\n    results = []\n    errors = []\n    for path in file_paths:\n        try:\n            with open(path) as f:\n                data = f.read()\n                result = data.upper()\n                results.append(result)\n        except FileNotFoundError:\n            logger.error(f'File not found: {path}')\n            errors.append({'path': str(path), 'error': 'file_not_found'})\n        except PermissionError:\n            logger.error(f'Permission denied: {path}')\n            errors.append({'path': str(path), 'error': 'permission_denied'})\n        except UnicodeDecodeError:\n            logger.error(f'Encoding error: {path}')\n            errors.append({'path': str(path), 'error': 'encoding_error'})\n        except Exception as e:\n            logger.error(f'Unexpected error processing {path}: {e}')\n            errors.append({'path': str(path), 'error': 'unexpected', 'detail': str(e)})\n    return {'results': results, 'errors': errors}\n"}},
        tools_required=["read", "edit"],
        max_turns=8,
        verification_script="code=open('broken.py').read(); assert 'try' in code and 'except' in code and 'errors' in code",
    ),
]


# ── CONVENIENCE ACCESS ──────────────────────────────────────────────

ALL_TASKS: list[Task] = (
    BASH_TASKS
    + EDIT_TASKS
    + READ_TASKS
    + WRITE_TASKS
    + MULTI_TOOL_TASKS
    + ERROR_RECOVERY_TASKS
)

TASKS_BY_ID: dict[str, Task] = {t.task_id: t for t in ALL_TASKS}
TASKS_BY_CATEGORY: dict[TaskCategory, list[Task]] = {
    TaskCategory.BASH: BASH_TASKS,
    TaskCategory.EDIT: EDIT_TASKS,
    TaskCategory.READ: READ_TASKS,
    TaskCategory.WRITE: WRITE_TASKS,
    TaskCategory.MULTI_TOOL: MULTI_TOOL_TASKS,
    TaskCategory.ERROR_RECOVERY: ERROR_RECOVERY_TASKS,
}


def get_task(task_id: str) -> Task | None:
    return TASKS_BY_ID.get(task_id)


def get_tasks_by_category(category: TaskCategory) -> list[Task]:
    return TASKS_BY_CATEGORY.get(category, [])


def get_all_task_ids() -> list[str]:
    return list(TASKS_BY_ID.keys())


def get_task_count() -> int:
    return len(ALL_TASKS)